FROM php:5.6.31-apache

LABEL maintainer=cwe@myschleppapp.de

# Enable ssh access to container.
RUN \
  apt-get update \ 
  && apt-get install -y --no-install-recommends openssh-server \
  && echo "root:Docker!" | chpasswd

# install the PHP extensions we need
RUN set -ex; \
	\
	apt-get update; \
	apt-get install -y \
		libjpeg-dev \
		libpng-dev \
	; \
	rm -rf /var/lib/apt/lists/*; \
	\
	docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
	docker-php-ext-install gd mysqli opcache
# TODO consider removing the *-dev deps and only keeping the necessary lib* packages

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=2'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN a2enmod rewrite expires \
	&& a2enmod ssl \
	&& a2enmod headers

#VOLUME /var/www/html
# we need the html stuff at /home/site/wwwroot

# copy files
COPY sshd_config /etc/ssh/
COPY 000-default.conf /etc/apache2/sites-available/
COPY apache2.conf /etc/apache2/

#### WARNING: remove confidential from wp-config.php before pushing to Docker Hub
RUN mkdir /usr/wpsrc
COPY wp/ /usr/wpsrc/

RUN chown -R www-data:www-data /usr/wpsrc

COPY docker-entrypoint.sh /usr/local/bin/

EXPOSE 2222 80 443

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["apache2-foreground"]
